FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && \
    apt-get install -y ffmpeg wget

# Instalar Poetry
RUN pip install poetry

# Copiar pyproject.toml y poetry.lock para instalar las dependencias
COPY pyproject.toml poetry.lock ./

# Instalar dependencias del proyecto usando Poetry
RUN poetry install

# Copiar el resto del código en el contenedor
COPY . .

CMD ["poetry", "run", "python3", "main.py"]
